server:
  port: 8765
---
spring:
  config:
    activate:
      on-profile: "dev"
  sleuth:
    sampler:
      probability: 1.0

# do not do discovery locator
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

