---
spring:
  config:
    activate:
      on-profile: "dev"
limits-service:
  minimum: 31
  maximum: 311
---
spring:
  config:
    activate:
      on-profile: "qa"
limits-service:
  minimum: 42
  maximum: 442
---
spring:
  config:
    activate:
      on-profile: "dokker"
limits-service:
  minimum: 89
  maximum: 1989
