---
spring:
  config:
    activate:
      on-profile: "dev"
limits-service:
  minimum: 31
  maximum: 311
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: "qa"
limits-service:
  minimum: 42
  maximum: 442
---
spring:
  config:
    activate:
      on-profile: "dokker"
limits-service:
  minimum: 19
  maximum: 89

eureka:
  client:
    service-url:
      default-zone: http://eureka-naming-server:8761/eureka
