server:
  port: 8761
---
spring:
  config:
    activate:
      on-profile: "dev"
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---

spring:
  config:
    activate:
      on-profile: "dokker"
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://zipkin-server:9411/

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
