server:
  port: 8761
---
spring:
  config:
    activate:
      on-profile: "dev"
  sleuth:
    sampler:
      probability: 1.0


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
