server:
  port: 8100

---
spring:
  config:
    activate:
      on-profile: "dev"
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
