server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: "dev"
  h2:
    console:
      enabled : true
      path : /h2_console
  datasource:
    url : jdbc:h2:mem:testdb
    username : sa
    password :
    driverClassName : org.h2.Driver
    initialization-mode : always
  jpa:
    hibernate:
      ddl-auto : none
    show-sql : true
    properties :
      hibernate :
        jdbc :
          lob :
            non_contextual_creation : true
          dialect : org.hibernate.dialect.HSQLDialect
  session:
    jdbc :
      initialize-schema : always
  sql :
    init :
      data-locations : classpath:schema.sql,classpath:data.sql

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      unstable_service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      unstable_service:
        maxAttempts: 5
        waitDuration: 2
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
     

---
spring:
  config:
    activate:
      on-profile: "qa"
  datasource:
     url : jdbc:mysql://localhost:3306/my_exchange
     username : pratheush
     password : Pratheush@18
     driverClassName : com.mysql.cj.jdbc.Driver
     initialization-mode : always
  jpa:
     hibernate:
        ddl-auto : update
     show-sql : true
     properties :
        hibernate :
           dialect : org.hibernate.dialect.MySQL5Dialect

  



